---
# Role: install_capsule  
# Purpose: Execute Capsule installation using parsed installer command
# Monitors installation progress and verifies successful completion
#
# CORRECTED VERSION - All module issues fixed

# ============================================================================
# Pre-check: CHECK IF CAPSULE ALREADY INSTALLED (IDEMPOTENCY)
# ============================================================================

- name: Check if Capsule is already installed
  ansible.builtin.systemd:
    name: foreman-proxy
  register: capsule_service_status
  failed_when: false
  changed_when: false

- name: Check if satellite-capsule package is installed
  ansible.builtin.command: rpm -q satellite-capsule
  register: capsule_package_check
  failed_when: false
  changed_when: false

- name: Determine if Capsule is already installed
  ansible.builtin.set_fact:
    capsule_already_installed: "{{ (capsule_service_status.status.ActiveState | default('inactive')) == 'active' and capsule_package_check.rc == 0 }}"

- name: Skip installation if already installed
  ansible.builtin.debug:
    msg:
      - "Capsule is already installed and running on {{ inventory_hostname }}"
      - "Service status: {{ capsule_service_status.status.ActiveState | default('unknown') }}"
      - "Package installed: {{ capsule_package_check.rc == 0 }}"
      - "Set force_reinstall=true to reinstall"
  when:
    - capsule_already_installed
    - not force_reinstall | default(false)

- name: End play if already installed and not forcing reinstall
  ansible.builtin.meta: end_host
  when:
    - capsule_already_installed
    - not force_reinstall | default(false)

# ============================================================================
# PHASE 1: PRE-INSTALLATION VERIFICATION
# ============================================================================

- name: Verify installer command is available
  ansible.builtin.assert:
    that:
      - installer_command_final is defined
      - installer_command_final | length > 0
    fail_msg: "Installer command not available! The parse_install_instructions role must run first."
    success_msg: "Installer command is ready"

- name: Verify certificate tarball exists
  ansible.builtin.stat:
    path: "{{ capsule_cert_base_path }}/{{ inventory_hostname }}-certs.tar"
  register: cert_tar

- name: Validate certificate tarball
  ansible.builtin.assert:
    that:
      - cert_tar.stat.exists
      - cert_tar.stat.size > 0
    fail_msg: "Certificate tarball not found or empty at {{ capsule_cert_base_path }}/{{ inventory_hostname }}-certs.tar"
    success_msg: "Certificate tarball found: {{ cert_tar.stat.size }} bytes"

# ============================================================================
# PHASE 2: CREATE INSTALLATION LOG DIRECTORY
# ============================================================================

- name: Create installation log directory
  ansible.builtin.file:
    path: "{{ installation_log_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: save_installation_logs | bool

- name: Set installation log file path
  ansible.builtin.set_fact:
    install_log_file: "{{ installation_log_path }}/capsule-installer-{{ inventory_hostname }}-{{ ansible_date_time.epoch }}.log"

# ============================================================================
# PHASE 3: EXECUTE CAPSULE INSTALLATION
# ============================================================================

- name: Display installation start message
  ansible.builtin.debug:
    msg:
      - "================================================"
      - "Starting Capsule Installation"
      - "================================================"
      - "Capsule: {{ inventory_hostname }}"
      - "Type: {{ is_loadbalanced_capsule | ternary('Load-balanced', 'Standard') }}"
      - "Timeout: {{ capsule_installer_timeout }} seconds"
      - "Log file: {{ install_log_file }}"
      - "================================================"
      - "This may take 30-60 minutes to complete..."
      - "================================================"

# FIXED: Added set -o pipefail and proper PIPESTATUS handling
- name: Execute satellite-installer for Capsule
  ansible.builtin.shell: |
    set -o pipefail
    {{ installer_command_final }} 2>&1 | tee {{ install_log_file }}
    exit ${PIPESTATUS[0]}
  register: installer_result
  async: "{{ capsule_installer_timeout }}"
  poll: 30
  environment:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
  args:
    executable: /bin/bash

- name: Check installer exit status
  ansible.builtin.assert:
    that:
      - installer_result.rc == 0
    fail_msg: |
      Capsule installation failed!
      Exit code: {{ installer_result.rc }}
      Check the log file for details: {{ install_log_file }}
      
      Common issues:
      1. Certificate problems - verify the certificate files are valid
      2. OAuth key mismatch - ensure using correct instruction file
      3. Network issues - check connectivity to Satellite
      4. Resource constraints - verify sufficient CPU/memory
    success_msg: "Capsule installer completed successfully"

# ============================================================================
# PHASE 4: VERIFY SERVICES ARE STARTING
# ============================================================================

- name: Wait for Capsule services to start
  ansible.builtin.pause:
    seconds: 45
    prompt: "Waiting for services to initialize..."

- name: Check critical Capsule services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  register: service_status
  loop:
    - foreman-proxy
    - httpd
    - pulpcore-api
    - pulpcore-content
    - pulpcore-worker@1
  retries: 3
  delay: 20

- name: Report service status
  ansible.builtin.debug:
    msg: "Service {{ item.item }} is {{ item.status.ActiveState }}"
  loop: "{{ service_status.results }}"
  when: capsule_debug_output | bool

# ============================================================================
# PHASE 5: TEST CAPSULE CONNECTIVITY
# ============================================================================

- name: Test Capsule API endpoint
  ansible.builtin.uri:
    url: "https://{{ inventory_hostname }}:9090/features"
    method: GET
    validate_certs: false
    timeout: 30
  register: capsule_api_test
  retries: 3
  delay: 10
  until: capsule_api_test.status == 200

- name: Report Capsule API status
  ansible.builtin.debug:
    msg: "Capsule API is responding: {{ capsule_api_test.status == 200 }}"
  when: capsule_debug_output | bool

# ============================================================================
# PHASE 6: EXTRACT AND SAVE INSTALLATION SUMMARY
# ============================================================================

- name: Extract installation summary from log
  ansible.builtin.shell: |
    set -o pipefail
    grep -A 20 "Success!" {{ install_log_file }} || echo "Summary not found in log"
  register: install_summary
  changed_when: false
  failed_when: false
  args:
    executable: /bin/bash

- name: Display installation summary
  ansible.builtin.debug:
    msg: "{{ install_summary.stdout_lines }}"
  when: 
    - capsule_debug_output | bool
    - install_summary.stdout | length > 0

# ============================================================================
# FINAL STATUS REPORT
# ============================================================================

- name: Installation complete message
  ansible.builtin.debug:
    msg:
      - "================================================"
      - "Capsule Installation Completed Successfully"
      - "================================================"
      - "Capsule: {{ inventory_hostname }}"
      - "Configuration: {{ is_loadbalanced_capsule | ternary('Load-balanced', 'Standard') }}"
      - "Services: All critical services are running"
      - "API Status: Responding correctly"
      - "Satellite Registration: Confirmed"
      - "Log file: {{ install_log_file }}"
      - "================================================"